sonar.projectKey=Cesi_Zen
sonar.projectName=Cesi_Zen
sonar.host.url=https://sonarcloud.io
sonar.sources=Cesi_Zen_API/api,Cesi_Zen_Front/CesiZen/src
sonar.exclusions=**/node_modules/**,**/migrations/**,**/*.spec.ts,Cesi_Zen_API/api/tests.py
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
