FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    default-libmysqlclient-dev \
    gcc \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
# On installe les requirements + les outils de test
RUN pip install --no-cache-dir -r requirements.txt pytest pytest-django

COPY . .

# Commande par défaut : lancer les tests
CMD ["pytest"]