# Generated by Django 6.0.3 on 2026-04-07 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_activite_delete_favoriactivite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.admin'),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.categorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
