# Generated by Django 6.0.3 on 2026-04-07 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_articleinfo_admin_articleinfo_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lecture', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.articleinfo')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.utilisateur')),
            ],
            options={
                'db_table': 'article_lu',
                'managed': True,
                'unique_together': {('utilisateur', 'article')},
            },
        ),
    ]
