# Generated by Django 6.0.3 on 2026-04-07 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_articlelu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelu',
            name='article',
            field=models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.articleinfo'),
        ),
        migrations.AlterField(
            model_name='articlelu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articlelu',
            name='utilisateur',
            field=models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.utilisateur'),
        ),
    ]
